export const SUPPORTED_COUNTRIES = [
  { name: "Afghanistan", code: "+93", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇦🇫" },
  { name: "Albania", code: "+355", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇦🇱" },
  { name: "Algeria", code: "+213", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇩🇿" },
  { name: "Andorra", code: "+376", phoneLength: 6, placeholder: "Enter 6-digit number", flag: "🇦🇩" },
  { name: "Angola", code: "+244", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇦🇴" },
  { name: "Argentina", code: "+54", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇦🇷" },
  { name: "Armenia", code: "+374", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇦🇲" },
  { name: "Australia", code: "+61", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇦🇺" },
  { name: "Austria", code: "+43", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇦🇹" },
  { name: "Azerbaijan", code: "+994", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇦🇿" },
  { name: "Bahamas", code: "+1", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇧🇸" },
  { name: "Bahrain", code: "+973", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇧🇭" },
  { name: "Bangladesh", code: "+880", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇧🇩" },
  { name: "Belarus", code: "+375", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇧🇾" },
  { name: "Belgium", code: "+32", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇧🇪" },
  { name: "Belize", code: "+501", phoneLength: 7, placeholder: "Enter 7-digit number", flag: "🇧🇿" },
  { name: "Benin", code: "+229", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇧🇯" },
  { name: "Bhutan", code: "+975", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇧🇹" },
  { name: "Bolivia", code: "+591", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇧🇴" },
  { name: "Bosnia and Herzegovina", code: "+387", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇧🇦" },
  { name: "Botswana", code: "+267", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇧🇼" },
  { name: "Brazil", code: "+55", phoneLength: 11, placeholder: "Enter 11-digit number", flag: "🇧🇷" },
  { name: "Brunei", code: "+673", phoneLength: 7, placeholder: "Enter 7-digit number", flag: "🇧🇳" },
  { name: "Bulgaria", code: "+359", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇧🇬" },
  { name: "Burkina Faso", code: "+226", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇧🇫" },
  { name: "Burundi", code: "+257", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇧🇮" },
  { name: "Cambodia", code: "+855", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇰🇭" },
  { name: "Cameroon", code: "+237", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇨🇲" },
  { name: "Canada", code: "+1", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇨🇦" },
  { name: "Cape Verde", code: "+238", phoneLength: 7, placeholder: "Enter 7-digit number", flag: "🇨🇻" },
  { name: "Central African Republic", code: "+236", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇨🇫" },
  { name: "Chad", code: "+235", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇹🇩" },
  { name: "Chile", code: "+56", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇨🇱" },
  { name: "China", code: "+86", phoneLength: 11, placeholder: "Enter 11-digit number", flag: "🇨🇳" },
  { name: "Colombia", code: "+57", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇨🇴" },
  { name: "Comoros", code: "+269", phoneLength: 7, placeholder: "Enter 7-digit number", flag: "🇰🇲" },
  { name: "Congo", code: "+242", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇨🇬" },
  { name: "Costa Rica", code: "+506", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇨🇷" },
  { name: "Croatia", code: "+385", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇭🇷" },
  { name: "Cuba", code: "+53", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇨🇺" },
  { name: "Cyprus", code: "+357", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇨🇾" },
  { name: "Czech Republic", code: "+420", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇨🇿" },
  { name: "Denmark", code: "+45", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇩🇰" },
  { name: "Djibouti", code: "+253", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇩🇯" },
  { name: "Dominica", code: "+1", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇩🇲" },
  { name: "Dominican Republic", code: "+1", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇩🇴" },
  { name: "Ecuador", code: "+593", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇪🇨" },
  { name: "Egypt", code: "+20", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇪🇬" },
  { name: "El Salvador", code: "+503", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇸🇻" },
  { name: "Equatorial Guinea", code: "+240", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇬🇶" },
  { name: "Eritrea", code: "+291", phoneLength: 7, placeholder: "Enter 7-digit number", flag: "🇪🇷" },
  { name: "Estonia", code: "+372", phoneLength: 7, placeholder: "Enter 7-digit number", flag: "🇪🇪" },
  { name: "Ethiopia", code: "+251", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇪🇹" },
  { name: "Fiji", code: "+679", phoneLength: 7, placeholder: "Enter 7-digit number", flag: "🇫🇯" },
  { name: "Finland", code: "+358", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇫🇮" },
  { name: "France", code: "+33", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇫🇷" },
  { name: "Gabon", code: "+241", phoneLength: 7, placeholder: "Enter 7-digit number", flag: "🇬🇦" },
  { name: "Gambia", code: "+220", phoneLength: 7, placeholder: "Enter 7-digit number", flag: "🇬🇲" },
  { name: "Georgia", code: "+995", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇬🇪" },
  { name: "Germany", code: "+49", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇩🇪" },
  { name: "Ghana", code: "+233", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇬🇭" },
  { name: "Greece", code: "+30", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇬🇷" },
  { name: "Grenada", code: "+1", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇬🇩" },
  { name: "Guatemala", code: "+502", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇬🇹" },
  { name: "Guinea", code: "+224", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇬🇳" },
  { name: "Guinea-Bissau", code: "+245", phoneLength: 7, placeholder: "Enter 7-digit number", flag: "🇬🇼" },
  { name: "Guyana", code: "+592", phoneLength: 7, placeholder: "Enter 7-digit number", flag: "🇬🇾" },
  { name: "Haiti", code: "+509", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇭🇹" },
  { name: "Honduras", code: "+504", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇭🇳" },
  { name: "Hungary", code: "+36", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇭🇺" },
  { name: "Iceland", code: "+354", phoneLength: 7, placeholder: "Enter 7-digit number", flag: "🇮🇸" },
  { name: "India", code: "+91", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇮🇳" },
  { name: "Indonesia", code: "+62", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇮🇩" },
  { name: "Iran", code: "+98", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇮🇷" },
  { name: "Iraq", code: "+964", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇮🇶" },
  { name: "Ireland", code: "+353", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇮🇪" },
  { name: "Israel", code: "+972", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇮🇱" },
  { name: "Italy", code: "+39", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇮🇹" },
  { name: "Jamaica", code: "+1", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇯🇲" },
  { name: "Japan", code: "+81", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇯🇵" },
  { name: "Jordan", code: "+962", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇯🇴" },
  { name: "Kazakhstan", code: "+7", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇰🇿" },
  { name: "Kenya", code: "+254", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇰🇪" },
  { name: "Kuwait", code: "+965", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇰🇼" },
  { name: "Kyrgyzstan", code: "+996", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇰🇬" },
  { name: "Laos", code: "+856", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇱🇦" },
  { name: "Latvia", code: "+371", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇱🇻" },
  { name: "Lebanon", code: "+961", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇱🇧" },
  { name: "Lesotho", code: "+266", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇱🇸" },
  { name: "Liberia", code: "+231", phoneLength: 7, placeholder: "Enter 7-digit number", flag: "🇱🇷" },
  { name: "Libya", code: "+218", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇱🇾" },
  { name: "Liechtenstein", code: "+423", phoneLength: 7, placeholder: "Enter 7-digit number", flag: "🇱🇮" },
  { name: "Lithuania", code: "+370", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇱🇹" },
  { name: "Luxembourg", code: "+352", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇱🇺" },
  { name: "Macedonia", code: "+389", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇲🇰" },
  { name: "Madagascar", code: "+261", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇲🇬" },
  { name: "Malawi", code: "+265", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇲🇼" },
  { name: "Malaysia", code: "+60", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇲🇾" },
  { name: "Maldives", code: "+960", phoneLength: 7, placeholder: "Enter 7-digit number", flag: "🇲🇻" },
  { name: "Mali", code: "+223", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇲🇱" },
  { name: "Malta", code: "+356", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇲🇹" },
  { name: "Mauritania", code: "+222", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇲🇷" },
  { name: "Mauritius", code: "+230", phoneLength: 7, placeholder: "Enter 7-digit number", flag: "🇲🇺" },
  { name: "Mexico", code: "+52", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇲🇽" },
  { name: "Moldova", code: "+373", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇲🇩" },
  { name: "Monaco", code: "+377", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇲🇨" },
  { name: "Mongolia", code: "+976", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇲🇳" },
  { name: "Montenegro", code: "+382", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇲🇪" },
  { name: "Morocco", code: "+212", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇲🇦" },
  { name: "Mozambique", code: "+258", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇲🇿" },
  { name: "Myanmar", code: "+95", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇲🇲" },
  { name: "Namibia", code: "+264", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇳🇦" },
  { name: "Nepal", code: "+977", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇳🇵" },
  { name: "Netherlands", code: "+31", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇳🇱" },
  { name: "New Zealand", code: "+64", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇳🇿" },
  { name: "Nicaragua", code: "+505", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇳🇮" },
  { name: "Niger", code: "+227", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇳🇪" },
  { name: "Nigeria", code: "+234", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇳🇬" },
  { name: "Norway", code: "+47", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇳🇴" },
  { name: "Oman", code: "+968", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇴🇲" },
  { name: "Pakistan", code: "+92", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇵🇰" },
  { name: "Panama", code: "+507", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇵🇦" },
  { name: "Papua New Guinea", code: "+675", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇵🇬" },
  { name: "Paraguay", code: "+595", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇵🇾" },
  { name: "Peru", code: "+51", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇵🇪" },
  { name: "Philippines", code: "+63", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇵🇭" },
  { name: "Poland", code: "+48", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇵🇱" },
  { name: "Portugal", code: "+351", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇵🇹" },
  { name: "Qatar", code: "+974", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇶🇦" },
  { name: "Romania", code: "+40", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇷🇴" },
  { name: "Russia", code: "+7", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇷🇺" },
  { name: "Rwanda", code: "+250", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇷🇼" },
  { name: "Saudi Arabia", code: "+966", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇸🇦" },
  { name: "Senegal", code: "+221", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇸🇳" },
  { name: "Serbia", code: "+381", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇷🇸" },
  { name: "Singapore", code: "+65", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇸🇬" },
  { name: "Slovakia", code: "+421", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇸🇰" },
  { name: "Slovenia", code: "+386", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇸🇮" },
  { name: "Somalia", code: "+252", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇸🇴" },
  { name: "South Africa", code: "+27", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇿🇦" },
  { name: "South Korea", code: "+82", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇰🇷" },
  { name: "Spain", code: "+34", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇪🇸" },
  { name: "Sri Lanka", code: "+94", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇱🇰" },
  { name: "Sudan", code: "+249", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇸🇩" },
  { name: "Sweden", code: "+46", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇸🇪" },
  { name: "Switzerland", code: "+41", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇨🇭" },
  { name: "Syria", code: "+963", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇸🇾" },
  { name: "Taiwan", code: "+886", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇹🇼" },
  { name: "Tajikistan", code: "+992", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇹🇯" },
  { name: "Tanzania", code: "+255", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇹🇿" },
  { name: "Thailand", code: "+66", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇹🇭" },
  { name: "Togo", code: "+228", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇹🇬" },
  { name: "Tunisia", code: "+216", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇹🇳" },
  { name: "Turkey", code: "+90", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇹🇷" },
  { name: "Turkmenistan", code: "+993", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇹🇲" },
  { name: "Uganda", code: "+256", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇺🇬" },
  { name: "Ukraine", code: "+380", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇺🇦" },
  { name: "UAE", code: "+971", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇦🇪" },
  { name: "United Kingdom", code: "+44", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇬🇧" },
  { name: "United States", code: "+1", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇺🇸" },
  { name: "Uruguay", code: "+598", phoneLength: 8, placeholder: "Enter 8-digit number", flag: "🇺🇾" },
  { name: "Uzbekistan", code: "+998", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇺🇿" },
  { name: "Venezuela", code: "+58", phoneLength: 10, placeholder: "Enter 10-digit number", flag: "🇻🇪" },
  { name: "Vietnam", code: "+84", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇻🇳" },
  { name: "Yemen", code: "+967", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇾🇪" },
  { name: "Zambia", code: "+260", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇿🇲" },
  { name: "Zimbabwe", code: "+263", phoneLength: 9, placeholder: "Enter 9-digit number", flag: "🇿🇼" }
];
